### ISSUE TITLE
[1.12] Unlocked Recipes won't show on JEI but are craftable (server only)

### ISSUE THREAD

**Issue by MasterEnderman** [jaredlll08/RecipeStages#18]
Forge: 14.23.3.2678
GameStages: 2.0.90
RecipeStages: 1.1.0
CraftTweaker: 4.1.8
MTLib: 3.0.4
JEI: 4.9.1.175

If a player on a server unlocked a gamestage the recipes for the staged items won't show up in JEI, but if you put the recipe in a crafting table you're able to craft the item.
This problem doesn't occur in singleplayer. There the recipes show up in JEI.

**Comment by MasterEnderman** [comment]
Fixed by an update.

**Comment by DarianLStephens** [comment]
An update to what? Everything in my modpack is up-to-date, but I still can't see the recipes in JEI, even in singleplayer.
An exception is when you _first_ get the game stage, but not when you reload the game after that.
